// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPOaDJAq4aN36l-Wcc02z20FLQySnKEE0',
    appId: '1:509048963365:web:83ab5c447d40b4a0dcdacc',
    messagingSenderId: '509048963365',
    projectId: 'qlma-b7d83',
    authDomain: 'qlma-b7d83.firebaseapp.com',
    storageBucket: 'qlma-b7d83.firebasestorage.app',
    measurementId: 'G-R2T9HGHQ74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMcV62BUU_ZfoQMja1mZljnDrnOUovFOc',
    appId: '1:509048963365:android:e771fef7c524f297dcdacc',
    messagingSenderId: '509048963365',
    projectId: 'qlma-b7d83',
    storageBucket: 'qlma-b7d83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBp7XP0BqAeKzjdSyeFzOh0Sbv2l2lDyY',
    appId: '1:509048963365:ios:9bcd94eda1358faddcdacc',
    messagingSenderId: '509048963365',
    projectId: 'qlma-b7d83',
    storageBucket: 'qlma-b7d83.firebasestorage.app',
    iosBundleId: 'com.example.qloder',
  );
}
